USE empresa2;

#Ejercicio 1
SELECT NOMBRE, LOCALIDAD, DEBE
FROM clientes
WHERE VENDEDOR_NO NOT IN (SELECT EMP_NO
									FROM empleados
									WHERE DEP_NO IN (SELECT DEP_NO
															FROM departamentos
															WHERE LOCALIDAD LIKE 'BARCELONA'))
		AND CLIENTE_NO IN (SELECT CLIENTE_NO
									FROM pedidos
									WHERE PRODUCTO_NO IN (SELECT PRODUCTO_NO
																	FROM productos
																	WHERE PRECIO_ACTUAL < 1000));
																	
#Ejercicio 2
SELECT distinct C.NOMBRE, C.LOCALIDAD, DEBE, D.DNOMBRE, PR.PRECIO_ACTUAL, DESCRIPCION
FROM clientes C JOIN empleados E ON C.VENDEDOR_NO = E.EMP_NO
	JOIN departamentos D ON D.DEP_NO = E.DEP_NO
	JOIN pedidos P ON C.CLIENTE_NO = P.CLIENTE_NO
	JOIN productos PR ON P.PRODUCTO_NO = PR.PRODUCTO_NO
WHERE D.LOCALIDAD NOT LIKE 'BARCELONA'
		AND PR.PRECIO_ACTUAL< 1000; 
		
#Ejercicio 3
SELECT NOMAP, DEP_NO, SALARIO
FROM empleados E
WHERE SALARIO IN (SELECT SALARIO
						FROM empleados E1
						WHERE E.DEP_NO = E1.DEP_NO
						AND E.EMP_NO != E1.EMP_NO
						GROUP BY SALARIO)
ORDER BY DEP_NO, salario;

#Ejercicio 4
SELECT P.PRODUCTO_NO, COUNT(PE.PEDIDO_NO)
FROM productos P LEFT JOIN pedidos PE ON P.PRODUCTO_NO = PE.PRODUCTO_NO
GROUP BY P.PRODUCTO_NO;

#Ejercico 5
SELECT D.DEP_NO, E.*, COUNT(E.EMP_NO)
FROM departamentos D JOIN empleados E ON D.DEP_NO = E.DEP_NO
WHERE E.SALARIO+IFNULL(E.COMISION,0) IN (SELECT MAX(E1.SALARIO+IFNULL(E1.COMISION,0))
						FROM empleados E1
						WHERE E.DEP_NO = E1.DEP_NO)
GROUP BY D.DEP_NO,E.DEP_NO;